//! The web panel, compiled into the binary.
//!
//! The reference mounts a directory; this serves the same files from `.rodata`.
//! That is deliberate rather than incidental: the whole argument for the rewrite
//! is one file you can `scp` to a router with 8 MB of flash, and a panel that
//! needs a directory beside it is a second thing to install and a second thing
//! to get wrong. It also removes a class of bug outright — no path traversal is
//! possible against a fixed table, because there is no filesystem to traverse.
//!
//! The table is generated by `build.rs` from `static/`, so adding a file to the
//! panel is enough; nothing here needs editing.

use crate::respond::Reply;

include!(concat!(env!("OUT_DIR"), "/panel_assets.rs"));

/// How long a browser may reuse a panel file without asking.
///
/// Short on purpose. The panel is tens of kilobytes over a LAN, and an upgrade
/// that leaves a stale `app.js` cached against a new API is a support problem
/// out of all proportion to the bytes saved. The ETag does the real work: a
/// reload costs a 304 and no body.
const CACHE_CONTROL: &str = "no-cache";

/// Serve a panel path, or `None` if it is not part of the panel.
///
/// `if_none_match` is the client's `If-None-Match` header.
pub fn serve(path: &str, if_none_match: Option<&str>) -> Option<Reply> {
    let asset = lookup(path)?;

    // A matching ETag means the client already has this exact file.
    if let Some(presented) = if_none_match {
        if etag_matches(presented, asset.etag) {
            return Some(
                Reply {
                    status: 304,
                    body: Vec::new(),
                    content_type: asset.content_type,
                    extra: Vec::new(),
                }
                .with_header("ETag", asset.etag)
                .with_header("Cache-Control", CACHE_CONTROL),
            );
        }
    }

    Some(
        Reply {
            status: 200,
            body: asset.bytes.to_vec(),
            content_type: asset.content_type,
            extra: Vec::new(),
        }
        .with_header("ETag", asset.etag)
        .with_header("Cache-Control", CACHE_CONTROL),
    )
}

/// Whether the panel has anything to serve at all.
pub fn is_present() -> bool {
    !ASSETS.is_empty()
}

pub fn asset_count() -> usize {
    ASSETS.len()
}

/// Total embedded size, for `/api/version` to report honestly.
pub fn embedded_bytes() -> usize {
    ASSETS.iter().map(|a| a.bytes.len()).sum()
}

/// Resolve a request path to an asset.
///
/// `/` maps to `index.html`, matching the reference's `html=True` mount. Nothing
/// else is inferred: a directory-ish path is a miss rather than a guess, so a
/// mistyped URL 404s instead of quietly returning the app shell.
fn lookup(path: &str) -> Option<&'static Asset> {
    let wanted = if path == "/" { "/index.html" } else { path };
    ASSETS.iter().find(|a| a.path == wanted)
}

/// `If-None-Match` may carry a list, and a proxy may have weakened the tag.
fn etag_matches(presented: &str, ours: &str) -> bool {
    presented.split(',').any(|candidate| {
        let candidate = candidate.trim();
        // `*` means "any representation I might have".
        candidate == "*" || strip_weak(candidate) == strip_weak(ours)
    })
}

fn strip_weak(tag: &str) -> &str {
    tag.strip_prefix("W/").unwrap_or(tag)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_panel_is_actually_embedded() {
        // A build that quietly shipped no panel would pass every other test here
        // while serving nothing at all.
        assert!(is_present(), "no panel assets were compiled in");
        assert!(
            asset_count() >= 10,
            "only {} assets -- the panel is more than that",
            asset_count()
        );
        assert!(embedded_bytes() > 50_000);
    }

    #[test]
    fn the_root_serves_the_app_shell() {
        let root = serve("/", None).expect("/ is served");
        let index = serve("/index.html", None).expect("index.html is served");
        assert_eq!(root.status, 200);
        assert_eq!(root.body, index.body);
        assert_eq!(root.content_type, "text/html; charset=utf-8");
        assert!(!root.body.is_empty());
    }

    #[test]
    fn modules_are_served_as_javascript_not_plain_text() {
        // The reason the reference registers MIME types at startup: a browser
        // refuses an ES module served as text/plain, and the whole panel is
        // modules.
        let js = serve("/js/app.js", None).expect("app.js is served");
        assert_eq!(js.content_type, "text/javascript; charset=utf-8");
        let css = serve("/css/styles.css", None).expect("styles.css is served");
        assert_eq!(css.content_type, "text/css; charset=utf-8");
    }

    #[test]
    fn a_path_outside_the_panel_is_not_served() {
        assert!(serve("/api/units", None).is_none());
        assert!(serve("/nope.js", None).is_none());
        assert!(serve("", None).is_none());
    }

    #[test]
    fn traversal_cannot_reach_anything() {
        // There is no filesystem behind this, so these are simply misses -- but
        // they are the first thing anyone tries, so they are worth pinning.
        for attempt in [
            "/../Cargo.toml",
            "/js/../../Cargo.toml",
            "/./index.html",
            "/js/%2e%2e/app.js",
            "//etc/passwd",
            "/index.html%00.js",
        ] {
            assert!(serve(attempt, None).is_none(), "{attempt} was served");
        }
    }

    #[test]
    fn a_known_etag_gets_a_304_with_no_body() {
        let first = serve("/index.html", None).unwrap();
        let tag = first
            .extra
            .iter()
            .find(|(n, _)| *n == "ETag")
            .map(|(_, v)| v.clone())
            .expect("an ETag is sent");

        let second = serve("/index.html", Some(&tag)).unwrap();
        assert_eq!(second.status, 304);
        assert!(second.body.is_empty(), "a 304 carries no body");

        // A stale tag gets the file.
        let third = serve("/index.html", Some("\"something-else\"")).unwrap();
        assert_eq!(third.status, 200);
        assert!(!third.body.is_empty());
    }

    #[test]
    fn etags_differ_between_files_and_are_stable_for_one() {
        let a = serve("/index.html", None).unwrap();
        let b = serve("/js/app.js", None).unwrap();
        let tag = |r: &Reply| {
            r.extra
                .iter()
                .find(|(n, _)| *n == "ETag")
                .map(|(_, v)| v.clone())
                .unwrap()
        };
        assert_ne!(tag(&a), tag(&b));
        assert_eq!(tag(&a), tag(&serve("/index.html", None).unwrap()));
        // Quoted, as HTTP requires.
        assert!(tag(&a).starts_with('"') && tag(&a).ends_with('"'));
    }

    #[test]
    fn a_weak_or_listed_etag_still_matches() {
        let first = serve("/index.html", None).unwrap();
        let tag = first
            .extra
            .iter()
            .find(|(n, _)| *n == "ETag")
            .map(|(_, v)| v.clone())
            .unwrap();

        // A proxy may weaken the tag, and a client may send several.
        assert_eq!(
            serve("/index.html", Some(&format!("W/{tag}")))
                .unwrap()
                .status,
            304
        );
        assert_eq!(
            serve("/index.html", Some(&format!("\"other\", {tag}")))
                .unwrap()
                .status,
            304
        );
        assert_eq!(serve("/index.html", Some("*")).unwrap().status, 304);
    }

    #[test]
    fn panel_files_are_not_cached_hard() {
        // An upgrade that leaves a stale app.js against a new API is a worse
        // problem than re-sending a few kilobytes on a LAN.
        let r = serve("/index.html", None).unwrap();
        let caching = r
            .extra
            .iter()
            .find(|(n, _)| *n == "Cache-Control")
            .map(|(_, v)| v.clone())
            .expect("Cache-Control is set");
        assert_eq!(caching, "no-cache");
        assert!(!caching.contains("max-age=3153600"), "not a year");
    }

    #[test]
    fn every_embedded_file_has_a_type_and_a_tag() {
        for asset in ASSETS {
            assert!(asset.path.starts_with('/'), "{}", asset.path);
            assert!(
                asset.content_type != "application/octet-stream",
                "{} was served as raw bytes -- add its type to build.rs",
                asset.path
            );
            assert!(asset.etag.starts_with('"'), "{}", asset.path);
            assert!(!asset.bytes.is_empty(), "{} is empty", asset.path);
        }
    }
}
