#!/usr/bin/env bash
# Build the FreeBSD binary, package and SIGNED pkg repository - on a real
# FreeBSD machine.
#
#   ./packaging/bsd/build-freebsd.sh [user@host]
#
# There is no cross-build: Zig bundles no FreeBSD libc, so a FreeBSD binary is
# compiled on FreeBSD. The machine needs cargo (pkg install rust) and doas.
#
# Output, fetched back here:
#   packaging/out/bin/freebsd-amd64/breeze-core
#   packaging/out/bsd/freebsd/            the signed repository
#   packaging/out/dist/breeze-core-<ver>-freebsd-amd64.tar.zst
#
# **The signing key visits that machine.** `pkg repo` signs locally, so the
# private key is copied over, used, and then shredded - the same procedure the
# Python line used for its BSD repositories. If this script dies between those
# steps, go and remove ~/bcn-build/signing.key on the target by hand.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO"
TARGET="${1:-monika@192.168.122.131}"
VER="$(grep -m1 '^version' crates/breeze-core/Cargo.toml | cut -d'"' -f2)"
KEY="packaging/repo/keys/aspic-freebsd.rsa"
WORK="bcn-build"

[ -f "$KEY" ] || { echo "no $KEY - it is generated by packaging/repo/build-repo.sh"; exit 1; }

COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
git diff --quiet HEAD 2>/dev/null || COMMIT="$COMMIT-dirty"

echo "=== $TARGET: $(ssh "$TARGET" 'uname -srm')"

echo "=== sending the source"
tar --exclude='./target' --exclude='./packaging/out' --exclude='./.git' -czf /tmp/bcn-src.tgz .
ssh "$TARGET" "rm -rf ~/$WORK && mkdir -p ~/$WORK"
scp -q /tmp/bcn-src.tgz "$TARGET:~/$WORK/"
ssh "$TARGET" "cd ~/$WORK && tar -xzf bcn-src.tgz && rm bcn-src.tgz"

echo "=== building"
ssh "$TARGET" "cd ~/$WORK && CARGO_HOME=\$HOME/$WORK/.cargo BREEZE_COMMIT=$COMMIT cargo build --release 2>&1 | tail -3"
ssh "$TARGET" "~/$WORK/target/release/breeze-core --version"

echo "=== packaging"
ssh "$TARGET" "cd ~/$WORK && sh packaging/bsd/mkpkg-freebsd.sh ~/$WORK/out 2>&1 | tail -2"

echo "=== signing the repository"
# The key goes over, gets used, and is destroyed. rm -P overwrites before
# unlinking, which is the FreeBSD equivalent of shred.
scp -q "$KEY" "$TARGET:~/$WORK/signing.key"
ssh "$TARGET" "
  set -e
  chmod 600 ~/$WORK/signing.key
  cd ~/$WORK/out
  pkg repo . ~/$WORK/signing.key
  rm -P ~/$WORK/signing.key
  echo '  key destroyed on the target:'
  ls ~/$WORK/signing.key 2>/dev/null && echo '  !! STILL THERE' || echo '  gone'
  ls -la
"

echo "=== fetching the artifacts back"
mkdir -p packaging/out/bin/freebsd-amd64 packaging/out/bsd/freebsd packaging/out/dist
scp -q "$TARGET:~/$WORK/out/*" packaging/out/bsd/freebsd/
scp -q "$TARGET:~/$WORK/target/release/breeze-core" packaging/out/bin/freebsd-amd64/breeze-core
tar --zstd -cf "packaging/out/dist/breeze-core-$VER-freebsd-amd64.tar.zst" \
    -C packaging/out/bin/freebsd-amd64 breeze-core -C "$REPO" LICENSE README.md

# The public half belongs in the tree, next to the repository it verifies.
cp packaging/repo/keys/aspic-freebsd.pub packaging/out/bsd/freebsd/aspic-freebsd.pub
chmod 644 packaging/out/bsd/freebsd/aspic-freebsd.pub

echo
ls -l packaging/out/bsd/freebsd/
echo
echo "verify it on the machine with:  ./packaging/bsd/verify-freebsd.sh $TARGET"
