//! Cross-implementation vectors: signatures produced by Breeze Core itself.
//!
//! `tests/fixtures/signing-vectors.json` was generated by the real
//! `security/signing.py` using pycryptodome — see
//! `fixtures/generate-vectors.py`. If these pass, this crate agrees with the
//! implementation the Android app, the web panel and the CLI were all built
//! against.
//!
//! Testing against my own signatures would only prove Rust agrees with Rust. The
//! canonical string is a contract between four implementations, so the vector has
//! to come from outside.

use base64::Engine;
use breeze_auth::signing;
use serde::Deserialize;

#[derive(Deserialize)]
struct Doc {
    public_key: String,
    canonical_prefix: String,
    skew_seconds: u64,
    vectors: Vec<Vector>,
}

#[derive(Deserialize)]
struct Vector {
    method: String,
    path: String,
    body_b64: String,
    timestamp: String,
    nonce: String,
    canonical_b64: String,
    body_sha3_512: String,
    signature: String,
}

fn load() -> Doc {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/signing-vectors.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("vectors are valid JSON")
}

fn b64_std(value: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(value)
        .expect("fixture base64")
}

#[test]
fn the_constants_agree() {
    let doc = load();
    assert_eq!(doc.canonical_prefix, signing::CANONICAL_PREFIX);
    assert_eq!(doc.skew_seconds, signing::DEFAULT_SKEW_SECONDS);
}

#[test]
fn the_public_key_from_python_is_accepted() {
    let doc = load();
    assert!(
        signing::public_key_is_valid(&doc.public_key),
        "pycryptodome's raw Ed25519 export must load"
    );
}

/// The canonical string this crate builds must be byte-identical to Python's.
///
/// This is the check that matters most: a signature can only verify if both
/// sides hashed exactly the same bytes, so a difference here would show up as
/// every request failing with `bad_signature` and no clue why.
#[test]
fn canonical_strings_match_python_byte_for_byte() {
    let doc = load();
    for v in &doc.vectors {
        let body = b64_std(&v.body_b64);
        let ours = signing::build_canonical(&v.method, &v.path, &v.timestamp, &v.nonce, &body);
        let theirs = b64_std(&v.canonical_b64);
        assert_eq!(
            String::from_utf8_lossy(&ours),
            String::from_utf8_lossy(&theirs),
            "canonical string differs for {} {}",
            v.method,
            v.path
        );
    }
}

#[test]
fn body_digests_match_python() {
    let doc = load();
    for v in &doc.vectors {
        let body = b64_std(&v.body_b64);
        assert_eq!(
            signing::sha3_512_hex(&body),
            v.body_sha3_512,
            "SHA3-512 differs for {} {} ({} body bytes)",
            v.method,
            v.path,
            body.len()
        );
    }
}

/// Every signature Python produced must verify here.
#[test]
fn python_signatures_verify() {
    let doc = load();
    assert!(!doc.vectors.is_empty(), "fixture must contain vectors");
    for v in &doc.vectors {
        let body = b64_std(&v.body_b64);
        let canonical = signing::build_canonical(&v.method, &v.path, &v.timestamp, &v.nonce, &body);
        assert!(
            signing::verify_signature(&doc.public_key, &canonical, &v.signature),
            "signature from Python did not verify for {} {}",
            v.method,
            v.path
        );
    }
}

/// And a signature must not verify against a request it was not made for --
/// otherwise "it verifies" would prove nothing.
#[test]
fn python_signatures_do_not_verify_for_other_requests() {
    let doc = load();
    for (i, v) in doc.vectors.iter().enumerate() {
        let other = &doc.vectors[(i + 1) % doc.vectors.len()];
        if other.path == v.path && other.method == v.method {
            continue;
        }
        let body = b64_std(&other.body_b64);
        let canonical = signing::build_canonical(
            &other.method,
            &other.path,
            &other.timestamp,
            &other.nonce,
            &body,
        );
        assert!(
            !signing::verify_signature(&doc.public_key, &canonical, &v.signature),
            "signature for {} {} wrongly verified against {} {}",
            v.method,
            v.path,
            other.method,
            other.path
        );
    }
}

/// A non-ASCII body is in the fixture on purpose: the digest is over raw bytes,
/// and a UTF-8 mishandling on either side would only show up here.
#[test]
fn a_non_ascii_body_digests_identically() {
    let doc = load();
    let v = doc
        .vectors
        .iter()
        .find(|v| b64_std(&v.body_b64).iter().any(|b| *b >= 0x80))
        .expect("fixture should include a non-ASCII body");
    let body = b64_std(&v.body_b64);
    assert_eq!(signing::sha3_512_hex(&body), v.body_sha3_512);
    let canonical = signing::build_canonical(&v.method, &v.path, &v.timestamp, &v.nonce, &body);
    assert!(signing::verify_signature(
        &doc.public_key,
        &canonical,
        &v.signature
    ));
}
