//! Compiles the web panel into the binary.
//!
//! Walks `static/` at the repo root and writes a table of
//! `(url path, content type, etag, bytes)` for `panel.rs` to serve. Generated
//! rather than hand-listed so a file added to the panel cannot be silently left
//! out — the failure mode of a hand-written table is a 404 nobody notices until
//! a page half-loads.
//!
//! The bytes are embedded with `include_bytes!`, so they live in `.rodata` and
//! cost no runtime allocation, and the whole panel travels with the one binary.
//! That is the point: `scp` one file to a router and the panel is there.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    // crates/breeze-http -> repo root.
    let root = manifest
        .parent()
        .and_then(Path::parent)
        .expect("repo root")
        .to_path_buf();
    let static_dir = root.join("static");

    println!("cargo:rerun-if-changed={}", static_dir.display());
    // `build_commit()` reads BREEZE_COMMIT through option_env!, which bakes the
    // value in at compile time but does *not* make cargo notice when it
    // changes. Without this line a release build that reuses a cached artifact
    // ships the previous build's commit — a wrong answer from /api/version and
    // /metrics that looks exactly like a right one.
    println!("cargo:rerun-if-env-changed=BREEZE_COMMIT");

    let mut files = Vec::new();
    collect(&static_dir, &static_dir, &mut files);
    // Sorted so the generated file is byte-stable between builds: an unstable
    // build artefact turns every rebuild into a relink.
    files.sort();

    if files.is_empty() {
        // Not fatal: a build with no panel still serves the API. Warn loudly
        // rather than shipping a mystery 404.
        println!(
            "cargo:warning=no panel files found under {} -- the web panel will 404",
            static_dir.display()
        );
    }

    let mut out = String::from(
        "// Generated by build.rs. Do not edit.\n\
         pub struct Asset {\n\
         \x20   pub path: &'static str,\n\
         \x20   pub content_type: &'static str,\n\
         \x20   pub etag: &'static str,\n\
         \x20   pub bytes: &'static [u8],\n\
         }\n\n\
         pub const ASSETS: &[Asset] = &[\n",
    );

    for relative in &files {
        let absolute = static_dir.join(relative);
        let url = format!("/{}", relative.replace('\\', "/"));
        let bytes = std::fs::read(&absolute).expect("read panel file");
        let _ = writeln!(
            out,
            "    Asset {{ path: {:?}, content_type: {:?}, etag: {:?}, \
             bytes: include_bytes!({:?}) }},",
            url,
            content_type(&url),
            etag(&bytes),
            absolute,
        );
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("out dir")).join("panel_assets.rs");
    std::fs::write(&dest, out).expect("write panel table");
}

fn collect(base: &Path, dir: &Path, found: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(base, &path, found);
        } else if let Ok(relative) = path.strip_prefix(base) {
            found.push(relative.to_string_lossy().into_owned());
        }
    }
}

/// The panel's own types only. Anything unrecognised is served as bytes rather
/// than guessed at — `X-Content-Type-Options: nosniff` means a wrong type is a
/// file the browser refuses, which is worse than a generic one.
fn content_type(url: &str) -> &'static str {
    match url.rsplit_once('.').map(|(_, ext)| ext) {
        Some("html") => "text/html; charset=utf-8",
        // The reason the reference registers MIME types at startup: a Windows
        // dev box serves .js as text/plain from the registry, and a browser
        // refuses a module with the wrong type.
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("ico") => "image/vnd.microsoft.icon",
        Some("woff2") => "font/woff2",
        _ => "application/octet-stream",
    }
}

/// A content-derived ETag, so a reload over WiFi costs a 304 rather than the
/// whole panel.
///
/// FNV-1a: not a security boundary, just a change detector, and it needs no
/// dependency in a build script. Length is mixed in so two files that collide on
/// the hash still differ.
fn etag(bytes: &[u8]) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for b in bytes {
        hash ^= *b as u64;
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("\"{:016x}-{:x}\"", hash, bytes.len())
}
