#!/usr/bin/env bash
# Assemble the Gentoo overlay into packaging/out/portage/.
#
#   ./packaging/portage/build-overlay.sh
#
# Gentoo's deliverable is not a package but an OVERLAY: a small repository of
# ebuilds that a user adds alongside the Gentoo tree. That is why there is no
# .tbz2 to sign and nothing to put in the aspic package repositories — a user
# adds the overlay, and portage fetches the release tarball from GitHub itself
# and checks it against the Manifest hashes generated here.
#
# Why an overlay is possible now, when the Python line never had one: an ebuild
# builds in a sandbox against the user's own USE flags and CHOST, so a Python
# package would have had to declare each of its forty dependencies at whatever
# version Gentoo happened to carry — a fork of the dependency tree, maintained
# forever. A statically linked executable has no ABI coupling to the host at
# all, which is the condition under which a -bin package is the idiomatic
# answer on Gentoo rather than a shortcut.
#
# The overlay is ASSEMBLED rather than checked in whole: the init script and
# the systemd unit are the canonical ones from packaging/nfpm/, copied in here.
# Two hand-maintained copies of an init script drift, and the copy that drifts
# is always the one nobody runs.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO"

SRC="packaging/portage"
OUT="packaging/out/portage"
DIST="packaging/out/dist"
VERSION="$(grep -m1 '^version' crates/breeze-core/Cargo.toml | cut -d'"' -f2)"
CAT="app-misc"
PN="breeze-core-bin"
PKGDIR="$OUT/$CAT/$PN"

# The Gentoo ebuild tree, as a data image. `ebuild manifest` needs it for the
# eclasses the ebuilds inherit (systemd, acct-user, acct-group) and for a
# usable profile; the stage3 image ships no tree of its own.
TREE_IMAGE="gentoo/portage:latest"
TREE_VOLUME="bc-portage-tree"
STAGE3="gentoo/stage3:amd64-openrc"

# our label | Gentoo distfile suffix (must match SRC_URI in the ebuild)
TARBALLS="
amd64|amd64
arm64|arm64
armv7|armv7
ppc64le|ppc64le
riscv64|riscv64
s390x|s390x
"

echo "=== assembling the aspic overlay for breeze-core-bin-$VERSION"

rm -rf "$OUT"
mkdir -p "$PKGDIR/files" "$OUT/metadata" "$OUT/profiles"

# --- skeleton ---------------------------------------------------------------
cp "$SRC/metadata/layout.conf"  "$OUT/metadata/"
cp "$SRC/profiles/repo_name"    "$OUT/profiles/"
cp "$SRC/profiles/categories"   "$OUT/profiles/"
cp -r "$SRC/acct-group" "$SRC/acct-user" "$OUT/"
cp "$SRC/$CAT/$PN/metadata.xml" "$PKGDIR/"

# The version lives in the filename and reaches the ebuild body as ${PV}, so
# the template needs no substitution — only a rename.
cp "$SRC/$CAT/$PN/$PN.ebuild.in" "$PKGDIR/$PN-$VERSION.ebuild"

# --- files/, from the canonical sources -------------------------------------
cp "$SRC/files/breeze-core.confd"          "$PKGDIR/files/breeze-core.confd"
cp "packaging/nfpm/breeze-core.initd"      "$PKGDIR/files/breeze-core.initd"
cp "packaging/nfpm/breeze-core.service"    "$PKGDIR/files/breeze-core.service"
echo "  files/  <- packaging/nfpm/{breeze-core.initd,breeze-core.service}"

# --- distfiles, under the names SRC_URI renames them to ---------------------
# `ebuild manifest` hashes whatever is in DISTDIR under the DESTINATION name,
# so the local tarballs have to be staged under the renamed names or portage
# tries to download them.
STAGEDIST="packaging/out/portage-distdir"
rm -rf "$STAGEDIST"
mkdir -p "$STAGEDIST"
missing=0
while IFS='|' read -r label suffix; do
  [ -n "$label" ] || continue
  src="$DIST/breeze-core-$VERSION-linux-$label.tar.zst"
  if [ ! -f "$src" ]; then
    echo "!! missing $src"
    missing=$((missing + 1))
    continue
  fi
  cp "$src" "$STAGEDIST/$PN-$VERSION-$suffix.tar.zst"
done <<< "$TARBALLS"

if [ "$missing" -gt 0 ]; then
  # Loud. A Manifest missing one architecture's DIST line makes that
  # architecture fail at fetch time for the user, not here.
  echo
  echo "!! $missing tarball(s) missing — run ./packaging/build-binaries.sh"
  exit 1
fi
echo "  distdir <- $(ls -1 "$STAGEDIST" | wc -l | tr -d ' ') tarballs"

# --- Manifest, generated by portage itself ---------------------------------
MOUNT="$REPO"
case "$MOUNT" in /[a-z]/*) MOUNT="$(echo "$MOUNT" | sed -E 's#^/([a-z])/#\U\1:/#')" ;; esac
export MSYS_NO_PATHCONV=1

# A named container holding only the ebuild tree, reused across runs. Created
# once; `docker create` on an existing name fails harmlessly.
if ! docker container inspect "$TREE_VOLUME" >/dev/null 2>&1; then
  echo "  creating the $TREE_VOLUME data container"
  docker create --name "$TREE_VOLUME" "$TREE_IMAGE" >/dev/null
fi

echo
echo "=== generating the Manifest (BLAKE2B + SHA512, by portage)"
docker run --rm \
  --volumes-from "$TREE_VOLUME" \
  -v "$MOUNT/$OUT:/overlay-ro:ro" \
  -v "$MOUNT/$STAGEDIST:/distdir:ro" \
  -e VERSION="$VERSION" \
  "$STAGE3" bash -eu -c '
    exec 3>&1 1>&2
    # The overlay mount is read-only and the Manifest is written next to the
    # ebuild, so work on a copy and stream the result back out.
    cp -a /overlay-ro /overlay
    mkdir -p /etc/portage/repos.conf
    cat > /etc/portage/repos.conf/aspic.conf <<EOF
[aspic]
location = /overlay
EOF
    # DISTDIR read-only would make portage try to write a lock file there.
    mkdir -p /var/cache/distfiles
    cp /distdir/*.tar.zst /var/cache/distfiles/
    echo "DISTDIR=\"/var/cache/distfiles\"" >> /etc/portage/make.conf
    # FEATURES: no sandbox, because there is nothing to build and the container
    # cannot unshare namespaces anyway — portage says so itself as "Unable to
    # unshare: EPERM" if they are left on. That means the network sandbox is
    # NOT what stops portage quietly downloading a different tarball than the
    # one staged here; verify-portage.sh re-hashes the local files and compares
    # them against this Manifest, which is a check that does not depend on the
    # container having privileges it does not have.
    echo "FEATURES=\"-sandbox -usersandbox -ipc-sandbox -network-sandbox -pid-sandbox digest\"" >> /etc/portage/make.conf

    cd /overlay/app-misc/breeze-core-bin
    ebuild "breeze-core-bin-${VERSION}.ebuild" manifest
    echo "--- Manifest ---"
    cat Manifest
    tar -cf - -C /overlay . >&3
  ' < /dev/null | tar -xf - -C "$OUT"

echo
echo "=== overlay tree"
find "$OUT" -type f | sed "s|^$OUT|  .|" | sort
echo
echo "=== Manifest"
sed 's/^/  /' "$PKGDIR/Manifest"
echo
echo "next: ./packaging/portage/verify-portage.sh   (emerges it in a Gentoo container)"
