"""Emit signed-request vectors using Breeze Core's real signing implementation.

Run inside a container that has the package and pycryptodome:

  docker run --rm -v <repo>:/src:ro -v <fixtures>:/out \
    --entrypoint /opt/breeze/venv/bin/python <image> /out/generate-vectors.py
"""
import base64
import json
import sys

sys.path.insert(0, "/src")
from Crypto.PublicKey import ECC
from Crypto.Signature import eddsa

from meow_ac.security import signing

def b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode().rstrip("=")

# A fixed key so the vectors are reproducible. seed= takes 32 bytes.
key = ECC.construct(curve="Ed25519", seed=bytes(range(32)))
public_raw = key.public_key().export_key(format="raw")
signer = eddsa.new(key, "rfc8032")

cases = [
    ("GET", "/api/units", b""),
    ("GET", "/api/units/state?all=1", b""),
    ("POST", "/api/units/153931628470980/control", b'{"power_state":true,"target_temperature":24.5}'),
    ("DELETE", "/api/timers/abc123", b""),
    # A body with non-ASCII, to pin the UTF-8 handling of the digest.
    ("POST", "/api/programs", '{"name":"Erkondišn"}'.encode("utf-8")),
]

vectors = []
for method, path, body in cases:
    timestamp = "1787488496"
    nonce = f"nonce-{len(vectors)}"
    canonical = signing.build_canonical(method, path, timestamp, nonce, body)
    signature = signer.sign(canonical)
    vectors.append({
        "method": method,
        "path": path,
        "body_b64": base64.b64encode(body).decode(),
        "timestamp": timestamp,
        "nonce": nonce,
        "canonical_b64": base64.b64encode(canonical).decode(),
        "body_sha3_512": signing.sha3_512_hex(body),
        "signature": b64(signature),
    })

doc = {
    "note": "Generated by Breeze Core's own security/signing.py -- do not hand-edit.",
    "public_key": b64(public_raw),
    "canonical_prefix": signing.CANONICAL_PREFIX,
    "skew_seconds": signing.DEFAULT_SKEW_SECONDS,
    "vectors": vectors,
}
with open("/out/signing-vectors.json", "w", encoding="utf-8", newline="") as f:
    json.dump(doc, f, indent=2)
print(f"  wrote {len(vectors)} vectors, public key {doc['public_key'][:16]}…")
